### ISSUE TITLE
Revoked tokens

### ISSUE THREAD

**Issue by AlcaDesign** [micantre/DeceBot#1]
I've revoked these OAuth tokens I found in your code:
```
uc83kc9uo4u90x2psnm7jyxvlv833i (itsdece)
7fgcs39add7sai7jibewmxzr6b7ydq (decebot)
```
Please make sure not to publish your OAuth tokens anywhere. Consider using environment variables or a file that is ignored by `.gitignore`  to load in these tokens.

The `tmi.js` option `connection.cluster` is no longer used:
```js
...
connection: {
    cluster: "aws", // Ignore this option
    ...
}
...
```

**Comment by macdude95** [comment]
Thanks for doing that! I'll be more careful in the future
